//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public decimal MABL { get; set; }
        public string NOIDUNGBL { get; set; }
        public Nullable<decimal> MATHANHVIEN { get; set; }
        public Nullable<decimal> MASP { get; set; }
    
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
