//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public decimal MACHITIETPN { get; set; }
        public Nullable<decimal> MAPN { get; set; }
        public Nullable<decimal> MASP { get; set; }
        public Nullable<long> DONGIANHAP { get; set; }
        public Nullable<decimal> SOLUONGNHAP { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
