//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONDATHANG
    {
        public decimal MACHITIETDDH { get; set; }
        public decimal MADDH { get; set; }
        public decimal MASP { get; set; }
        public string TENSP { get; set; }
        public decimal SOLUONG { get; set; }
        public long DONGIA { get; set; }
    
        public virtual DONDATHANG DONDATHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
