//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATHANG()
        {
            this.CHITIETDONDATHANGs = new HashSet<CHITIETDONDATHANG>();
        }
    
        public decimal MADDH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<decimal> TINHTRANGGIAO { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public Nullable<decimal> DATHANHTOAN { get; set; }
        public Nullable<decimal> MATHANHVIEN { get; set; }
        public Nullable<decimal> UUDAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDATHANG> CHITIETDONDATHANGs { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
