//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public decimal ID { get; set; }
        public string THONGTIN { get; set; }
        public Nullable<decimal> TRANGTHAI { get; set; }
        public string HOTEN { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string YEUCAU { get; set; }
    }
}
