//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONDATHANGs = new HashSet<CHITIETDONDATHANG>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
        }
    
        public decimal MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string CAUHINH { get; set; }
        public string MOTA { get; set; }
        public string HINHANH { get; set; }
        public Nullable<decimal> SOLUONGTON { get; set; }
        public Nullable<decimal> LUOTXEM { get; set; }
        public Nullable<decimal> LUOTBINHCHON { get; set; }
        public Nullable<decimal> SOLANMUA { get; set; }
        public Nullable<decimal> MOI { get; set; }
        public Nullable<decimal> DAXOA { get; set; }
        public Nullable<decimal> MANCC { get; set; }
        public Nullable<decimal> MANSX { get; set; }
        public Nullable<decimal> MALOAISP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDATHANG> CHITIETDONDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
